// CA1720 is disabled because EF projection enums intentionally use canonical type words such as String,
// Numeric, and External to align with the published specification and metadata surface.
#pragma warning disable CA1720
using SemanticTypeModel.Abstractions.Hardening;

namespace SemanticTypeModel.EFCore;

/// <summary>
/// Represents the EF Core-like projection result for a hardened semantic type model.
/// </summary>
public sealed record EfModelDefinition
{
    /// <summary>
    /// Gets the projected model name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// Gets projected entity types, including owned types when configured.
    /// </summary>
    public required IReadOnlyList<EfEntityTypeDefinition> EntityTypes { get; init; }

    /// <summary>
    /// Gets projection diagnostics.
    /// </summary>
    public required IReadOnlyList<SchemaDiagnostic> Diagnostics { get; init; }
}

/// <summary>
/// Represents a projected EF Core-like entity type definition.
/// </summary>
public sealed record EfEntityTypeDefinition
{
    /// <summary>
    /// Gets the projected entity type name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// Gets the projected table name when applicable.
    /// </summary>
    public string? TableName { get; init; }

    /// <summary>
    /// Gets the projected schema name when applicable.
    /// </summary>
    public string? SchemaName { get; init; }

    /// <summary>
    /// Gets projected scalar, enum, flattened, serialized, or owned-navigation properties.
    /// </summary>
    public required IReadOnlyList<EfPropertyDefinition> Properties { get; init; }

    /// <summary>
    /// Gets projected key definitions.
    /// </summary>
    public required IReadOnlyList<EfKeyDefinition> Keys { get; init; }

    /// <summary>
    /// Gets projected relationship definitions declared for this entity.
    /// </summary>
    public required IReadOnlyList<EfRelationshipDefinition> Relationships { get; init; }

    /// <summary>
    /// Gets a value indicating whether this entity definition represents an owned/value object projection.
    /// </summary>
    public bool IsOwned { get; init; }

    /// <summary>
    /// Gets carried annotations.
    /// </summary>
    public required AnnotationBag Annotations { get; init; }
}

/// <summary>
/// Represents a projected EF Core-like property definition.
/// </summary>
public sealed record EfPropertyDefinition
{
    /// <summary>
    /// Gets the projected property name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// Gets the CLR type selected for the projection.
    /// </summary>
    public required Type ClrType { get; init; }

    /// <summary>
    /// Gets a value indicating whether property presence is required by canonical semantics.
    /// </summary>
    public bool IsRequired { get; init; }

    /// <summary>
    /// Gets a value indicating whether the projected value may be null.
    /// </summary>
    public bool IsNullable { get; init; }

    /// <summary>
    /// Gets the maximum string length when available.
    /// </summary>
    public int? MaxLength { get; init; }

    /// <summary>
    /// Gets numeric precision metadata when available.
    /// </summary>
    public NumericPrecision? Precision { get; init; }

    /// <summary>
    /// Gets the projected column name when applicable.
    /// </summary>
    public string? ColumnName { get; init; }

    /// <summary>
    /// Gets optional conversion metadata.
    /// </summary>
    public string? Conversion { get; init; }

    /// <summary>
    /// Gets a value indicating whether the value is generated by the store or adapter contract.
    /// </summary>
    public bool IsGenerated { get; init; }

    /// <summary>
    /// Gets carried annotations, including preserved schema presence/nullability markers.
    /// </summary>
    public required AnnotationBag Annotations { get; init; }
}

/// <summary>
/// Represents a projected EF Core-like key definition.
/// </summary>
public sealed record EfKeyDefinition
{
    /// <summary>
    /// Gets the projected key name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// Gets projected property names participating in the key.
    /// </summary>
    public required IReadOnlyList<string> PropertyNames { get; init; }

    /// <summary>
    /// Gets the projected key kind.
    /// </summary>
    public required EfKeyKind Kind { get; init; }

    /// <summary>
    /// Gets a value indicating whether the key is generated.
    /// </summary>
    public bool IsGenerated { get; init; }
}

/// <summary>
/// Represents a projected EF Core-like relationship definition.
/// </summary>
public sealed record EfRelationshipDefinition
{
    /// <summary>
    /// Gets the relationship name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// Gets the principal entity name.
    /// </summary>
    public required string PrincipalEntity { get; init; }

    /// <summary>
    /// Gets the dependent entity name.
    /// </summary>
    public required string DependentEntity { get; init; }

    /// <summary>
    /// Gets projected principal-side property names.
    /// </summary>
    public required IReadOnlyList<string> PrincipalProperties { get; init; }

    /// <summary>
    /// Gets projected dependent-side property names.
    /// </summary>
    public required IReadOnlyList<string> DependentProperties { get; init; }

    /// <summary>
    /// Gets the projected relationship cardinality.
    /// </summary>
    public required EfRelationshipCardinality Cardinality { get; init; }

    /// <summary>
    /// Gets the projected delete behavior.
    /// </summary>
    public EfDeleteBehavior DeleteBehavior { get; init; }

    /// <summary>
    /// Gets carried annotations.
    /// </summary>
    public required AnnotationBag Annotations { get; init; }
}

/// <summary>
/// Defines EF Core-like key kinds.
/// </summary>
public enum EfKeyKind
{
    /// <summary>Primary key.</summary>
    Primary,

    /// <summary>Alternate key.</summary>
    Alternate,

    /// <summary>Unique index representation.</summary>
    UniqueIndex,

    /// <summary>Surrogate key.</summary>
    Surrogate,

    /// <summary>External identity marker.</summary>
    External,
}

/// <summary>
/// Defines EF Core-like relationship cardinality.
/// </summary>
public enum EfRelationshipCardinality
{
    /// <summary>One-to-one.</summary>
    OneToOne,

    /// <summary>One-to-many.</summary>
    OneToMany,

    /// <summary>Many-to-one.</summary>
    ManyToOne,

    /// <summary>Many-to-many.</summary>
    ManyToMany,
}

/// <summary>
/// Defines EF Core-like delete behavior.
/// </summary>
public enum EfDeleteBehavior
{
    /// <summary>No explicit delete behavior.</summary>
    Unspecified,

    /// <summary>Restrict delete behavior.</summary>
    Restrict,

    /// <summary>Cascade delete behavior.</summary>
    Cascade,

    /// <summary>Set null delete behavior.</summary>
    SetNull,

    /// <summary>No action delete behavior.</summary>
    NoAction,
}
#pragma warning restore CA1720
